version: '3'
services:
  pcl-container:
    build:
      context: .
      dockerfile: humble.dockerfile
    image: elaina/ros2_host_hamble
    container_name: ros2_host_humble_container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ${WSL_X11_SOCKET:-/tmp/.X11-unix}:/tmp/.X11-unix
      - ./../../:/home/Elaina/docker
      # - ~/.config/fish:/home/Elaina/.config/fish
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    # runtime: "nvidia"
    entrypoint: [ "/bin/bash", "-c", "-i", "source /opt/ros/humble/setup.bash && ros2 run ros_tcp_endpoint default_server_endpoint" ]
    working_dir: "/home/Elaina" # 指定默认工作目录
